### ISSUE TITLE
Unable to get cookie

### ISSUE THREAD

**Issue by MrsZ** [xtekky/TikTok-Cookies#1]
Hi，run the py
my result is
{
    "passport_csrf_token": "2a8ced24e40b30b4f866fc580638e4a3",
    "passport_csrf_token_default": "2a8ced24e40b30b4f866fc580638e4a3"
}

![image](https://user-images.githubusercontent.com/13742821/186828095-eda1dd46-83ca-411b-9dda-1310bdbaee55.png)

Is that the wrong place？

**Comment by xtekky** [comment]
which cookie are you looking for ?

**Comment by MrsZ** [comment]
get the  tiktok login cookie

**Comment by MrsZ** [comment]
by the cookie, to request others api

**Comment by xtekky** [comment]
to actually login, the process is 10x more complex and needs a lot of ressources
